'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Strings
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("CircuitDrawing.Strings", GetType(Strings).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Auf Verbinder ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property AufVerbinder() As String
            Get
                Return ResourceManager.GetString("AufVerbinder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Mitte ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Ausrichtung_Mitte() As String
            Get
                Return ResourceManager.GetString("Ausrichtung_Mitte", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Oben ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Ausrichtung_Oben() As String
            Get
                Return ResourceManager.GetString("Ausrichtung_Oben", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Unten ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Ausrichtung_Unten() As String
            Get
                Return ResourceManager.GetString("Ausrichtung_Unten", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Kein Bauteil ausgewählt. Das Tastenkürzel kann nicht initialisiert werden. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Bauteil_Nicht_Vorhanden() As String
            Get
                Return ResourceManager.GetString("Bauteil_Nicht_Vorhanden", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Berechnung Abbrechen? ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property BerechnungAbbrechen() As String
            Get
                Return ResourceManager.GetString("BerechnungAbbrechen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Bereit ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Bereit() As String
            Get
                Return ResourceManager.GetString("Bereit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Die Berechnung dauert sehr lange, soll die Berechnung abgebrochen werden? ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property BezierLangeZeit() As String
            Get
                Return ResourceManager.GetString("BezierLangeZeit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Blocksatz ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Blocksatz() As String
            Get
                Return ResourceManager.GetString("Blocksatz", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Breite ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Breite() As String
            Get
                Return ResourceManager.GetString("Breite", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Standardstile ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DefaultEinstellung() As String
            Get
                Return ResourceManager.GetString("DefaultEinstellung", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Bauelemente ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DefaultEinstellung_Bauteile() As String
            Get
                Return ResourceManager.GetString("DefaultEinstellung_Bauteile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Standard-Schriftart ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DefaultEinstellung_Font() As String
            Get
                Return ResourceManager.GetString("DefaultEinstellung_Font", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Sonstige Grafikelemente ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DefaultEinstellung_Grafikelemente() As String
            Get
                Return ResourceManager.GetString("DefaultEinstellung_Grafikelemente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Strom- und Spannungspfeile ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DefaultEinstellung_StromSpannungspfeile() As String
            Get
                Return ResourceManager.GetString("DefaultEinstellung_StromSpannungspfeile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Verbinder ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DefaultEinstellung_Verbinder() As String
            Get
                Return ResourceManager.GetString("DefaultEinstellung_Verbinder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Einstellungen ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Detect_Einstellungen() As String
            Get
                Return ResourceManager.GetString("Detect_Einstellungen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Abstand: ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Einstellung_Abstand() As String
            Get
                Return ResourceManager.GetString("Einstellung_Abstand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Abstand der Beschriftung ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Einstellung_AbstandBeschriftung() As String
            Get
                Return ResourceManager.GetString("Einstellung_AbstandBeschriftung", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Abstand Pfeil ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Einstellung_AbstandPfeil() As String
            Get
                Return ResourceManager.GetString("Einstellung_AbstandPfeil", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Quer: ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Einstellung_AbstandQuer() As String
            Get
                Return ResourceManager.GetString("Einstellung_AbstandQuer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Anzahl ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Einstellung_Anzahl() As String
            Get
                Return ResourceManager.GetString("Einstellung_Anzahl", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Art des Strompfeiles ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Einstellung_ArtDesStrompfeiles() As String
            Get
                Return ResourceManager.GetString("Einstellung_ArtDesStrompfeiles", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Beschriftung ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Einstellung_Beschriftung() As String
            Get
                Return ResourceManager.GetString("Einstellung_Beschriftung", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Deckkraft: ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Einstellung_Deckkraft() As String
            Get
                Return ResourceManager.GetString("Einstellung_Deckkraft", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Einfach ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Einstellung_Einfach() As String
            Get
                Return ResourceManager.GetString("Einstellung_Einfach", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Farbe: ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Einstellung_Farbe() As String
            Get
                Return ResourceManager.GetString("Einstellung_Farbe", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Ändern ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Einstellung_Farbe_Ändern() As String
            Get
                Return ResourceManager.GetString("Einstellung_Farbe_Ändern", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Art: ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Einstellung_FontArt() As String
            Get
                Return ResourceManager.GetString("Einstellung_FontArt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Größe: ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Einstellung_Fontsize() As String
            Get
                Return ResourceManager.GetString("Einstellung_Fontsize", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Schriftart ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Einstellung_Fontstyle() As String
            Get
                Return ResourceManager.GetString("Einstellung_Fontstyle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Füllstil ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Einstellung_Füllstil() As String
            Get
                Return ResourceManager.GetString("Einstellung_Füllstil", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Funktion ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Einstellung_Funktion() As String
            Get
                Return ResourceManager.GetString("Einstellung_Funktion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Größe ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Einstellung_Größe() As String
            Get
                Return ResourceManager.GetString("Einstellung_Größe", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Krümmung ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Einstellung_Krümmung() As String
            Get
                Return ResourceManager.GetString("Einstellung_Krümmung", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Abstand: ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Einstellung_KrümmungAbstand() As String
            Get
                Return ResourceManager.GetString("Einstellung_KrümmungAbstand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Rundheit: ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Einstellung_KrümmungRundheit() As String
            Get
                Return ResourceManager.GetString("Einstellung_KrümmungRundheit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Länge (parallel) ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Einstellung_LaengePfeil_p() As String
            Get
                Return ResourceManager.GetString("Einstellung_LaengePfeil_p", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Länge (senkrecht) ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Einstellung_LaengePfeil_s() As String
            Get
                Return ResourceManager.GetString("Einstellung_LaengePfeil_s", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Linienstil ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Einstellung_Linienstil() As String
            Get
                Return ResourceManager.GetString("Einstellung_Linienstil", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Mehrere Rechtecke ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Einstellung_MehrereRechtecke() As String
            Get
                Return ResourceManager.GetString("Einstellung_MehrereRechtecke", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Pfeilspitze ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Einstellung_Pfeilspitze() As String
            Get
                Return ResourceManager.GetString("Einstellung_Pfeilspitze", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Pfeilspitzen ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Einstellung_Pfeilspitzen() As String
            Get
                Return ResourceManager.GetString("Einstellung_Pfeilspitzen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Abgerundete Ecken ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Einstellung_Rundes_Rechteck() As String
            Get
                Return ResourceManager.GetString("Einstellung_Rundes_Rechteck", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Radius: ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Einstellung_Rundes_Rechteck_Radius() As String
            Get
                Return ResourceManager.GetString("Einstellung_Rundes_Rechteck_Radius", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Stärke: ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Einstellung_Stärke() As String
            Get
                Return ResourceManager.GetString("Einstellung_Stärke", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Stil: ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Einstellung_Stil() As String
            Get
                Return ResourceManager.GetString("Einstellung_Stil", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Art: ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Einstellung_StrompfeilArt() As String
            Get
                Return ResourceManager.GetString("Einstellung_StrompfeilArt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Stützstellen ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Einstellung_Stützstellen() As String
            Get
                Return ResourceManager.GetString("Einstellung_Stützstellen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Ausrichtung: ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Einstellung_Textausrichtung() As String
            Get
                Return ResourceManager.GetString("Einstellung_Textausrichtung", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Horizontal: ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Einstellung_Textausrichtung_Horizontal() As String
            Get
                Return ResourceManager.GetString("Einstellung_Textausrichtung_Horizontal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Textausrichtung ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Einstellung_Textausrichtung_Textfeld() As String
            Get
                Return ResourceManager.GetString("Einstellung_Textausrichtung_Textfeld", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Vertikal: ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Einstellung_Textausrichtung_Vertikal() As String
            Get
                Return ResourceManager.GetString("Einstellung_Textausrichtung_Vertikal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Typ ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Einstellung_Typ() As String
            Get
                Return ResourceManager.GetString("Einstellung_Typ", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &lt;Verschiedene Werte&gt; ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Einstellung_VariousString() As String
            Get
                Return ResourceManager.GetString("Einstellung_VariousString", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Anzeige ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Einstellungspanel_Anzeige() As String
            Get
                Return ResourceManager.GetString("Einstellungspanel_Anzeige", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Bauelemente Bibliothek ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Einstellungspanel_Bauelemente() As String
            Get
                Return ResourceManager.GetString("Einstellungspanel_Bauelemente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Tastenkürzel - Bauelemente ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Einstellungspanel_ShortcutKeyBauteile() As String
            Get
                Return ResourceManager.GetString("Einstellungspanel_ShortcutKeyBauteile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Ende ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Ende() As String
            Get
                Return ResourceManager.GetString("Ende", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Fehler ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Fehler() As String
            Get
                Return ResourceManager.GetString("Fehler", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Höhe ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Höhe() As String
            Get
                Return ResourceManager.GetString("Höhe", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Kein Tastenkürzel ausgewählt. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property keinShortCutKeySelected() As String
            Get
                Return ResourceManager.GetString("keinShortCutKeySelected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Entf ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Key_Entf() As String
            Get
                Return ResourceManager.GetString("Key_Entf", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Leertaste ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Key_Leertaste() As String
            Get
                Return ResourceManager.GetString("Key_Leertaste", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die UMSCHALT ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Key_shift() As String
            Get
                Return ResourceManager.GetString("Key_shift", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Dieses Tastenkürzel wird schon verwendet und kann nicht neu zugeordnet werden. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property KeySchonBenutzt() As String
            Get
                Return ResourceManager.GetString("KeySchonBenutzt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Latex-Export ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property LatexExport() As String
            Get
                Return ResourceManager.GetString("LatexExport", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Links ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Links() As String
            Get
                Return ResourceManager.GetString("Links", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Linksbündig ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Linksbündig() As String
            Get
                Return ResourceManager.GetString("Linksbündig", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Für diese Funktion muss genau ein Verbinder ausgewählt sein! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MinCutFehlerEinVerbinder() As String
            Get
                Return ResourceManager.GetString("MinCutFehlerEinVerbinder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Mittlere Maustaste ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Mittlere_Maustaste() As String
            Get
                Return ResourceManager.GetString("Mittlere_Maustaste", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Neben Verbinder ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property NebenVerbinder() As String
            Get
                Return ResourceManager.GetString("NebenVerbinder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Neues Textfeld ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Neues_Textfeld() As String
            Get
                Return ResourceManager.GetString("Neues_Textfeld", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Nummerierung ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Nummerierung() As String
            Get
                Return ResourceManager.GetString("Nummerierung", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Oben ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Oben() As String
            Get
                Return ResourceManager.GetString("Oben", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Rechts ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Rechts() As String
            Get
                Return ResourceManager.GetString("Rechts", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Rechtsbündig ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Rechtsbündig() As String
            Get
                Return ResourceManager.GetString("Rechtsbündig", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Normal ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Rotation_Normal() As String
            Get
                Return ResourceManager.GetString("Rotation_Normal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die 180° gedreht ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Rotation180() As String
            Get
                Return ResourceManager.GetString("Rotation180", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die 270° gedreht ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Rotation270() As String
            Get
                Return ResourceManager.GetString("Rotation270", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die 90° gedreht ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Rotation90() As String
            Get
                Return ResourceManager.GetString("Rotation90", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Normal ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Skill_Drehung0() As String
            Get
                Return ResourceManager.GetString("Skill_Drehung0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die 180 Grad gedreht ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Skill_Drehung180() As String
            Get
                Return ResourceManager.GetString("Skill_Drehung180", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die 270 Grad gedreht ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Skill_Drehung270() As String
            Get
                Return ResourceManager.GetString("Skill_Drehung270", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die 90 Grad gedreht ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Skill_Drehung90() As String
            Get
                Return ResourceManager.GetString("Skill_Drehung90", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Kein Bauteil zuordnen ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Skill_Kein_Bauteil_Zuordnen() As String
            Get
                Return ResourceManager.GetString("Skill_Kein_Bauteil_Zuordnen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Gespiegelt X ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Skill_MX() As String
            Get
                Return ResourceManager.GetString("Skill_MX", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Gespiegelt X + 90 Grad gedreht ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Skill_MX_Rot90() As String
            Get
                Return ResourceManager.GetString("Skill_MX_Rot90", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Gespiegelt Y ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Skill_MY() As String
            Get
                Return ResourceManager.GetString("Skill_MY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Gespiegelt Y + 90 Grad gedreht ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Skill_MY_Rot90() As String
            Get
                Return ResourceManager.GetString("Skill_MY_Rot90", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Post-Routing Optimierungen ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Skill_PostRoutingOptimierung() As String
            Get
                Return ResourceManager.GetString("Skill_PostRoutingOptimierung", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Symbol importieren ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Skill_Symbol_importieren() As String
            Get
                Return ResourceManager.GetString("Skill_Symbol_importieren", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Sprache ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Sprache() As String
            Get
                Return ResourceManager.GetString("Sprache", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Bezierkurve: Klicken und ziehen für Startpunkt und klicken und ziehen für Endpunkt. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Tool_AddBezier() As String
            Get
                Return ResourceManager.GetString("Tool_AddBezier", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Bezierkurve zeichnen: Klicke und ziehe mit der Maus die gewünschte Kurve nach, die anschließend als Bezierkurve approximiert wird. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Tool_AddBezierFreihand() As String
            Get
                Return ResourceManager.GetString("Tool_AddBezierFreihand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Bus: Klicken um Bus-Beschriftung hinzuzufügen. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Tool_AddBus() As String
            Get
                Return ResourceManager.GetString("Tool_AddBus", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Strom: Klicken um Strompfeil zu platzieren. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Tool_AddCurrentArrow() As String
            Get
                Return ResourceManager.GetString("Tool_AddCurrentArrow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Zeichne Ellipse: Klicke und ziehe mit gedrückter Maustaste eine Ellipse auf. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Tool_AddEllipse() As String
            Get
                Return ResourceManager.GetString("Tool_AddEllipse", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Zeichne Form: Klicke und ziehe mit gedrückter Maustaste eine Form auf. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Tool_AddForm() As String
            Get
                Return ResourceManager.GetString("Tool_AddForm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Beschriftung: Klicken um Beschriftung hinzuzufügen. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Tool_AddLabel() As String
            Get
                Return ResourceManager.GetString("Tool_AddLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Linie: Einmal klicken für Startpunkt und einmal klicken für Endpunkt. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Tool_AddLine() As String
            Get
                Return ResourceManager.GetString("Tool_AddLine", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Zeichne Rechteck: Klicke und ziehe mit gedrückter Maustaste ein Rechteck auf. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Tool_AddRect() As String
            Get
                Return ResourceManager.GetString("Tool_AddRect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Zeichne rundes Rechteck: Klicke und ziehe mit gedrückter Maustaste ein rundes Rechteck auf. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Tool_AddRountRect() As String
            Get
                Return ResourceManager.GetString("Tool_AddRountRect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Zeichne Textfeld: Klicke und ziehe mit gedrückter Maustaste ein Textfeld auf. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Tool_AddTextfeld() As String
            Get
                Return ResourceManager.GetString("Tool_AddTextfeld", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Entfernen: Wählen Sie Elemente zum Entfernen aus. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Tool_Delete() As String
            Get
                Return ResourceManager.GetString("Tool_Delete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Verschieben: Klicke auf Element zum Verschieben. Klicke ein zweites Mal um es loszulassen. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Tool_Move() As String
            Get
                Return ResourceManager.GetString("Tool_Move", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Hinzufügen: Platzieren Sie Bauteile durch klicken. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Tool_Place() As String
            Get
                Return ResourceManager.GetString("Tool_Place", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Scale: Mit Maus Kante zum skalieren anklicken und dann verschieben. Ein zweites mal klicken zum loslassen der Kante. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Tool_Scale() As String
            Get
                Return ResourceManager.GetString("Tool_Scale", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Impedanz: Klicken um Impedanzpfeil zu platzieren. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ToolAddImpedanz() As String
            Get
                Return ResourceManager.GetString("ToolAddImpedanz", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Tools ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Tools() As String
            Get
                Return ResourceManager.GetString("Tools", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Copy: Bauteile zum Kopieren anklicken und verschieben. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Tools_BauteileKopieren() As String
            Get
                Return ResourceManager.GetString("Tools_BauteileKopieren", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Klicken um Start und Endpunkt festzulegen. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Tools_ClickToAddStartAndEnd() As String
            Get
                Return ResourceManager.GetString("Tools_ClickToAddStartAndEnd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Wire: Einmal klicken für Startpunkt und einmal klicken für Endpunkt. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Tools_DrawWire() As String
            Get
                Return ResourceManager.GetString("Tools_DrawWire", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Snappoint hinzufügen: Klicken Sie, um einen Snappoint hinzuzufügen. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Tools_SnappointHinzufügen() As String
            Get
                Return ResourceManager.GetString("Tools_SnappointHinzufügen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Snappoint löschen: Klicke auf Snappoint um ihn zu löschen. Hinweis: Snappoints die fest an Bauteile aus der Bibliothek verknüpft sind können nicht gelöscht werden. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Tools_SnappointLöschen() As String
            Get
                Return ResourceManager.GetString("Tools_SnappointLöschen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Spannungspfeil hinzufügen ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Tools_SpannungspfeilHinzufügen() As String
            Get
                Return ResourceManager.GetString("Tools_SpannungspfeilHinzufügen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die zum Drehen. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Tools_ZumDrehen() As String
            Get
                Return ResourceManager.GetString("Tools_ZumDrehen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die zum Durchschalten der Beschriftung. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Tools_ZumDurchschaltenDerBeschriftung() As String
            Get
                Return ResourceManager.GetString("Tools_ZumDurchschaltenDerBeschriftung", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die zum Durchschalten der Pfeilspitze. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Tools_ZumDurchschaltenDerPfeilspitze() As String
            Get
                Return ResourceManager.GetString("Tools_ZumDurchschaltenDerPfeilspitze", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die zum horizontal Spiegeln. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Tools_zumHSpiegeln() As String
            Get
                Return ResourceManager.GetString("Tools_zumHSpiegeln", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die zum Snappen an nächsten Verbinder. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Tools_ZumSnappenAmNächstenVerbinder() As String
            Get
                Return ResourceManager.GetString("Tools_ZumSnappenAmNächstenVerbinder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die zum vertikal Spiegeln. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Tools_zumVSpiegeln() As String
            Get
                Return ResourceManager.GetString("Tools_zumVSpiegeln", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Unten ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Unten() As String
            Get
                Return ResourceManager.GetString("Unten", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Bauelemente ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property WR_NAME_Bauelemente() As String
            Get
                Return ResourceManager.GetString("WR_NAME_Bauelemente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Einstellungen ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property WR_NAME_Einstellungen() As String
            Get
                Return ResourceManager.GetString("WR_NAME_Einstellungen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Auswahleinstellungen ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property WR_NAME_MarkierungsEinstellungen() As String
            Get
                Return ResourceManager.GetString("WR_NAME_MarkierungsEinstellungen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Zentriert ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Zentriert() As String
            Get
                Return ResourceManager.GetString("Zentriert", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
